pyipmi/ipmitool.py, pyipmi/msgs/picmg.py, pyipmi/picmg.py
The changes in this branch were made when adapting python-ipmi tool for our application and hardware. I've only included the changes which aren't specific to our hardware and should be applicable with any interface and target hardware. Please review and merge if you're happy with them.
=> Misc ipmitools and picmg improvements

pyipmi/bmc.py, pyipmi/constants.py, pyipmi/errors.py, pyipmi/fru.py, pyipmi/helper.py, pyipmi/hpm.py, pyipmi/interfaces/__init__.py, pyipmi/interfaces/ipmb.py, pyipmi/interfaces/ipmitool.py, pyipmi/lan.py, pyipmi/msgs/bmc.py, pyipmi/msgs/constants.py, pyipmi/msgs/message.py, pyipmi/picmg.py, pyipmi/sdr.py, pyipmi/sel.py, pyipmi/sensor.py, pyipmi/utils.py
=> remove pylint warnings

pyipmi/sdr.py, tests/test_sdr.py
Signed-off-by: Heiko Thiery <heiko.thiery@kontron.com>
=> fix sdr _convert_complement function

pyipmi/interfaces/rmcp.py
=> interfaces: rmcp: add copyright

pyipmi/interfaces/rmcp.py
=> interfaces: rmcp: remove unused code

tests/interfaces/test_rmcp.py
=> interfaces: rmcp: add test case

pyipmi/interfaces/ipmitool.py
Signed-off-by: Kari Koskinen <kari.koskinen@kotiposti.net>
=> ipmitool: add support for 'open' interface

docs/source/bmcWatchdog_cmd.rst, docs/source/chassis_cmd.rst, docs/source/ipmDevGlobal_cmd.rst, docs/source/ipmiMsgSupport_cmd.rst, docs/source/quick_start.rst, pyipmi/chassis.py, pyipmi/msgs/chassis.py
I reviewed my last files, and made some minor corrections.
=> Typo corrections after review

.gitignore, pyipmi/messaging.py, pyipmi/msgs/device_messaging.py, setup.py, tests/msgs/test_device_messaging.py
=> Add user channel access

setup.py
=> setup.py: add python 3.7/3.8

pyipmi/interfaces/rmcp.py
[_send_and_receive()](https://github.com/kontron/python-ipmi/blob/c0dc39a58ceb6a20bdbb8e8422d35fd9a70a273a/pyipmi/interfaces/rmcp.py#L493) sends a UDP datagram and waits for the answer.
It is called by two threads at the same time (see [establish_session()](https://github.com/kontron/python-ipmi/blob/c0dc39a58ceb6a20bdbb8e8422d35fd9a70a273a/pyipmi/interfaces/rmcp.py#L469)). This patch introduces a lock to fix that race condition.
=> Fix race condition in RMCP transaction

README.rst
=> Add tested devices

pyipmi/msgs/picmg.py
=> msg: picmg: fix PmHeartbeat command

tests/msgs/test_picmg.py
=> tests: add PmHeartbeat tests

pyipmi/interfaces/ipmitool.py, tests/interfaces/test_ipmitool.py
Revised Pull Request of [the previous pull request](https://github.com/kontron/python-ipmi/pull/122). The Codacy Complaint should be addressed now.
=> Added Handeling for 'target is None' ipmitool.py

tests/msgs/test_picmg.py
=> tests: add picmg tests

.github/workflows/publish.yml, .github/workflows/test.yml
=> actions: pin action repos and runner to versions

pyipmi/fru.py
Do not read the full FRU inventory area before parsing. This saves a lot of time when e.g. the area size is 8kByte but the areas only uses some bytes for the information stored there.
=> fru: implement adaptive fru inventory read

pyipmi/messaging.py, pyipmi/msgs/device_messaging.py, tests/msgs/test_device_messaging.py, tests/test_device_messaging.py
This pull request aims to add support for : 
- Get/SetUserAccess commands (manage privilege and permissions for IPMI users)
- SetUserPassword command (manage user password, enable / disable IPMI user)
=> Add User access and User password support

pyipmi/interfaces/rmcp.py, tests/interfaces/test_rmcp.py
This PR aims to solve the following issue #140 .
It adds a sort of feature flag `check_sdu_length` in `IpmiMsg` constructor, which is enabled by default so the current behavior doesn't change.
When deactivated, this allows to ignore the verification `len(pdu) = header_len + data_len`. This will also return everything contained in the `pdu[header_len:]` array rather than just `pdu[header_len:header_len + data_len]`  .
It only concerns legacy RMCP interface. I agree that the code should not be modified to complain with a buggy IPMI implementation, but I saw that `ipmitool` also ignore this verification when using legacy RMCP, so I thought this could be done here too.
The flag can be used when creating the IPMI interface :
```python
interfaces.create_interface(
interface="rmcp", …
```
=> Feature flag to disable rmcp sdu length verification

.github/workflows/test.yml
Add a test/check that a DOC (Developer Certificate of Origin) is present.
Thus this is used: https://github.com/christophebedard/dco-check
It requires a present "Signed-off-by" tag in the commit message.
=> actions: add dco check

pyipmi/interfaces/rmcp.py
This aims to fix issue #159 :
- raise a RetryError instead of an "Unassigned variable" exception if we exceed the `self.max_retries` during the transaction loop
- prevent from looping indefinitely when checking for mismatch between request header and received data if the ipmi message is not a bridged message
Perhaps it's better to use a TimeoutError for the transaction loop because we only increase the `retry` counter on `socket.timeout` exception, I'm not sure.
This can require further testing as it take care of a quite annoying to reproduce bug.
=> rmcp: fix transaction retry infinite loop

pyipmi/messaging.py
=> add missing return to __str__ method
