kontron/python-ipmi

- setup.py
Fixed setup.py in python 3 if git fails and fallback version getter is used.
Does nothing to comply with pep 440 for version formatting.
> Fix setup.py in python3

- pyipmi/__init__.py
- pyipmi/bmc.py
- pyipmi/chassis.py
- pyipmi/event.py
- pyipmi/fields.py
- pyipmi/fru.py
- pyipmi/hpm.py
- pyipmi/interfaces/aardvark.py
- pyipmi/interfaces/ipmb.py
- pyipmi/interfaces/ipmitool.py
- pyipmi/interfaces/mock.py
- pyipmi/ipmitool.py
- pyipmi/lan.py
- pyipmi/msgs/message.py
- pyipmi/msgs/picmg.py
- pyipmi/msgs/registry.py
- pyipmi/picmg.py
- pyipmi/sdr.py
- pyipmi/sel.py
- pyipmi/sensor.py
- pyipmi/state.py
- pyipmi/utils.py
> remove "from builtins import"

- pyipmi/errors.py
- pyipmi/hpm.py
- pyipmi/interfaces/aardvark.py
- pyipmi/interfaces/ipmitool.py
- pyipmi/msgs/message.py
- pyipmi/sdr.py
- pyipmi/sel.py
> change methods that could be a function

- pyipmi/interfaces/rmcp.py
> interfaces: rmcp: remove ord()

- pyipmi/interfaces/rmcp.py
> interfaces: rmcp: remove trailing whitespace

- pyipmi/sdr.py
Some of the units fields were not used in SDR's, here is a fix for storing them in the returned object.
> A fix for two unutilized sdr units fields

- pyipmi/fields.py
- pyipmi/hpm.py
- pyipmi/interfaces/ipmb.py
- pyipmi/interfaces/ipmitool.py
- pyipmi/interfaces/rmcp.py
- pyipmi/lan.py
- pyipmi/sdr.py
- pyipmi/utils.py
- tests/interfaces/test_rmcp.py
* Fix SyntaxWarning: "is not" with a literal. Did you mean "!="?
* Add py3_array_frombytes() and py3_array_tobytes() to pyipmi.utils.
frombytes() and tostring() methods of array.array have been removed
from Python 3.9.
* Python 3.9 normalizes the encoding name "bcd+" to "bcd".
* Replace b'...' with br'...' in two regular expressions.
* Add _PY3 private constant to pyipmi.utils.
> Update to Python 3.9

- tests/test_fru.py
- tests/test_hpm.py
The release tarball does not contain `tests/hpm_bin/firmware.hpm` and `tests/fru_bin/kontron_am4010.bin`.
> Skip FRU test cases if FRU test file is missing

- pyipmi/utils.py
Following Python code fails:
```python
interface = pyipmi.interfaces.create_interface(interface='ipmitool', interface_type='lanplus')
ipmi = pyipmi.create_connection(interface)
ipmi.session.set_session_type_rmcp(host=fqdn, port=port)
ipmi.session.set_auth_type_user(username=username, password=password)
ipmi.target = pyipmi.Target()
ipmi.session.establish()
ipmi_info = ipmi.get_device_id()
```
```
Traceback (most recent call last):
File "example.py", line 7
ipmi_info = ipmi.get_device_id()
File "pyipmi/bmc.py", line 25, in get_device_id
return DeviceId(self.send_message_with_name('GetDeviceId'))
File "pyipmi/__init__.py", line 206, in send_message_with_name
rsp = self.send_message(req)
File "pyipmi/__init__.py", line 190, in send_message
rsp = self.interface.send_and_receive(req)
File …
```
> Fix AttributeError: 'ByteBuffer' object has no attribute 'tobytes'

- pyipmi/interfaces/ipmitool.py
- tests/interfaces/test_ipmitool.py
I got a use case where ipmitool doesn't fail, but prepends the raw data with a error message line, probably due to a MicroTCA MCH failing a capabilities request. The requested IPMI access as such does succeed and data is printed out.
example:
```
$ ipmitool -I lan -H 192.168.1.209 -A NONE -T 0x82 -B 0 -t 0x7a -b 7 raw 0x30 0xf0 0x00
Get HPM.x Capabilities request failed, compcode = c9
4d 4d 43 20 43 6f 6e 73 6f 6c 65
```
`pyipmi.interfaces.ipmitool.send_and_receive_raw()` tries to parse the error message as hex dump (see below)
This patch throws out all error message lines (those that contain the word 'failed') to make sure ipmitool's hex output is still parsed.
```
Running ipmitool "ipmitool -I lan -H 192.168.1.209 -p 623 -U "" -P "" -T 0x82 -B 0 -t 0x7a -b 7 -l 0 raw 0x30 0xf0 0x00 …
```
> Make ipmitool interface robust against prepended error messages

- pyipmi/sdr.py
- tests/test_sdr.py
As discussed in https://github.com/kontron/python-ipmi/issues/99, this change will allow `sdr_repository_entries()` to finish iterating when an unknown record is found.
> Add SdrUnknownSensorRecord to allow fully iterating a SDR repository

- pyipmi/interfaces/rmcp.py
- pyipmi/ipmitool.py
- pyipmi/picmg.py
- cmd_id was renamed in the last commit - but not in rmcp.py
- 'is' is to compare instances, '==' should be used to compare values
- 'propery' -> 'property' in comments
> minor fixes

- README.rst
- pyipmi/interfaces/__init__.py
- pyipmi/interfaces/ipmbdev.py
- pyipmi/ipmitool.py
Add support of /dev/ipmb-X devices created by ipmb-dev-int driver on Linux.
Requires slave mode support by the I2C bus driver, list of such drivers can be seen this way:
https://elixir.bootlin.com/linux/latest/C/ident/i2c_slave_event
Tested on a Xilinx Zynq as Linux host with IPMB-0 bus of a NAT power supply.
> interfaces: add ipmbdev

- pyipmi/interfaces/ipmitool.py
pyipmi throws confusing error messages when ipmitool interface is used but ipmitool is not installed on the system,
example:
```
File "/home/jan/.local/lib/python3.8/site-packages/pyipmi/__init__.py", line 225, in raw_command
return self.interface.send_and_receive_raw(self.target, lun, netfn,
File "/home/jan/.local/lib/python3.8/site-packages/pyipmi/interfaces/ipmitool.py", line 143, in send_and_receive_raw
cc, rsp = self._parse_output(output)
File "/home/jan/.local/lib/python3.8/site-packages/pyipmi/interfaces/ipmitool.py", line 124, in _parse_output
rsp = array('B', [
File "/home/jan/.local/lib/python3.8/site-packages/pyipmi/interfaces/ipmitool.py", line 125, in <listcomp>
int(value, 16) for value in hexstr.split(' ')
```
This patch checks the returncode of the shell invoking ipmitool …
> interfaces.ipmitool: Throw exception if ipmitool not found

- pyipmi/interfaces/rmcp.py
The first reply acknowledges reception of the SEND_MESSAGE request from the
bridge, while the second one contains the forwarded reply
Signed-off-by: Emilio Perez <emilio.perez-juarez@diamond.ac.uk>
> interface.rmcp: allow SEND_MESSAGE answer to arrive in the next packet

- pyipmi/ipmitool.py
SDR type 0x13 has no field device_id_string and will throw an exception. Avoid this by setting device_id_string to 'None' in that case.
> ipmitool.py: fix issue with printing SDR type 0x13

- pyipmi/chassis.py
- pyipmi/lan.py
- pyipmi/msgs/chassis.py
- tests/msgs/test_chassis.py
- tests/test_chassis.py
- tests/test_lan.py
This pull request aims to add support for setting boot mode and boot device, and add some useful methods to abstract how to set VLAN ID, mac address, ip source and boot options without having to deal with bit manipulation.
- Add Get/Set SystemBootOptions request and response definitions in msgs/chassis.py
- Add helpers methods to easily manipulate lan parameters in lan.py
- Add helpers methods to easily manipulate boot options in chassis.py
I'm willing to contribute to this project so do not hesitate to tell me if I'm doing something wrong !
> Support SystemBootOptions commands and add boot/lan helpers methods

- pyipmi/messaging.py
- pyipmi/msgs/device_messaging.py
- tests/msgs/test_device_messaging.py
The `SetUserAccess` command has an Optional byte for "User Session Limit" (Section 22.26 of IPMI spec). This byte should be set to `0x00` by default and not `0x01` as it was here before (my mistake).
Moreover, when testing on a OCP Leopard BMC (from Quanta), the `SetUserAccess` command fail with an error code `Request data length invalid` because this byte was not present in the request payload. This PR adds the possibility to set the "User Session Limit" and make sure this byte is always present in the request.
> Fix set user access optional byte

- pyipmi/interfaces/aardvark.py
- pyipmi/ipmitool.py
VITA introduces a feature to switch IPMB frequency from 100kHz to 400kHz. This is called fastmode. To support this with the aardvark interface switching the freqency is added.
Co-Developed-by: Michel Ferland <michel.ferland@kontron.com>
> interface/aardvark: add support for fastmode

- pyipmi/__init__.py
- pyipmi/chassis.py
- pyipmi/errors.py
- pyipmi/interfaces/rmcp.py
- pyipmi/lan.py
- pyipmi/messaging.py
- pyipmi/msgs/constants.py
- pyipmi/utils.py
- tests/test_utils.py
This PR aims to add some command-specific completion code descriptions.
Some descriptions were already written but never used, so I add the corresponding dictionary to the `CompletionCodeError` implementation. This dictionary also needs the corresponding command ID in order to find the description so I add a reference to the command ID in places where `check_completion_code` is called and where I'm sure the specific CC descriptions exist for this command.
> Add cmd error code descr

- pyipmi/lan.py
- tests/test_lan.py
There is a possibility where the BMC can have the vlan tagging option disabled, but it still has a vlan ID stored in its memory.
In that case, a call to `get_lan_config_param` to know the vlan ID will return the vlan ID of the BMC, but the caller will have no information about whether the vlan is actually enable or not.
To avoid this confusing behavior, I choose to return vlan ID = 0 as a "convention" when the vlan is disabled, but this can be debated obviously.
> lan: return vlan id = 0 if vlan is deactivated

- .github/workflows/test.yml
- setup.py
The `import __futur__` and `import future` are two different things, but easily mistaken.
The python3-future library is being now removed from Debian, which makes your software uninstallable.
Luckilly you don't _actually_ need it.
This PR clears it up.
Je vous rencontre bientôt à Bruxelles.
> remove extraneous dependency on "future"

- pyipmi/ipmitool.py
Initially chassis status is only supported.
> ipmitool: add option for json output

- .github/workflows/test.yml
- setup.py
- tests/interfaces/test_ipmitool.py
- tests/test_helper.py
- tests/test_hpm.py
- tests/test_ipmi.py
- tests/test_ipmitool.py
- tests/test_sel.py
- tests/test_sensor.py
https://github.com/testing-cabal/mock
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
> replace old "mock" by "unittest.mock" from the standard library

- README.rst
- examples/interface_rmcp.py
- pyipmi/interfaces/rmcp.py
After PR  #144 was merged, I tried to connect to a BMC using an "OPERATOR" user with interface "rmcp", but I kept getting error messages such as :
```
CompletionCodeError cc=0x86 desc=requested maximum privilege level exceeds user and/or channel privilege limit
```
It works perfectly with interface "ipmitool".
I think this error comes from the `_activate_session` method in `pyipmi/interfaces/rmcp.py`, which uses a hardcoded `Session.PRIV_LEVEL_ADMINISTRATOR` by default. If the BMC user only has "OPERATOR" privilege for example, trying to establish a session with maximum privilege requested set to "ADMINISTRATOR" it will result in an "Insufficient privilege" IPMI error.
---
I have also added an example of `set_priv_level` usage in the README and in the examples/ folder to show how it is …
> Set rmcp session privilege level in session activation

- pyipmi/bmc.py
- pyipmi/msgs/bmc.py
- pyipmi/msgs/message.py
- tests/msgs/test_bmc.py
- tests/test_bmc.py
This change adds support to issue the command 'Get Device GUID'. Additionally, a couple of minor issues were also fixed.
> Support for Get Device GUID

- pyipmi/interfaces/ipmitool.py
- pyipmi/ipmitool.py
- tests/interfaces/test_ipmitool.py
- tests/test_ipmitool.py
add support to set the cipher for ipmitool.
was also requested in #161
> support setting cipher for ipmitool

- pyipmi/errors.py
- pyipmi/interfaces/ipmitool.py
- tests/interfaces/test_ipmitool.py
The given IPMI password can be longer than IPMI expect. In that case the _parse_output method in Ipmitool's will output the following error "invalid literal for int() with base 16: 'lanplus:'". While if we look at the line that was taken from IPMI we will see that its "lanplus: password is longer than 20 bytes.". So the issue is that there is no check for this error and the function skips it and tries to convert that string from a hex into an integer. I have added an execption, regex check and the match check.
> fix: add long password ipmi error

- pyipmi/interfaces/ipmitool.py
- tests/interfaces/test_ipmitool.py
Ignore lines with "Received a response with unexpected ID" in ipmitool output.
Add unit test for case.
Fixes https://github.com/kontron/python-ipmi/issues/182
> ipmi: ignore unexpected id lines
